fix(ui): Change UI container port to 8080 to work with new nginx image
syndesisio/openshift-templates pull request #73
Opened 2017-08-16 16:12 UTC by jimmidyson

Fixes #72

2017-08-16 17:42 UTC, rhuss requested changes
You should regenerate the templates, otherwise lgtm

2017-08-17 08:44 UTC, rhuss commented
@jimmidyson any change you can recreate the templates ? If not, no problem I can do it. But need your agreement ;-)

2017-08-17 08:47 UTC, jimmidyson commented
Doh! Sorry - done now.

2017-08-17 08:48 UTC, rhuss approved these changes
LGTM

2017-08-17 08:48 UTC, merged

2017-08-17 08:54 UTC, rhuss commented on generator/03-syndesis-ui.yml.mustache
>            - containerPort: 2015
@jimmidyson shouldn't this be adapted to 8080, too ?

2017-08-17 08:57 UTC, jimmidyson commented
Bugger - submitted #74